// Renames every symbol this copy of the wormhole exports, so that it can be
// linked into one binary alongside another copy of Diva's wormhole, which
// defines the same names. Included by lib.h after its system headers, so it
// reaches every wormhole source file and every C++ file that includes Diva,
// but never a libc declaration.
//
// Generated, apart from debug_assert below. After changing the wormhole
// sources, regenerate by compiling kv.c lib.c wh.c wh_int.c and listing their
// exports,
//   nm -g --defined-only *.o | awk 'NF==3{print $3}' | sort -u
// taking the union over WORMHOLE_GLOBAL_SLAB, WORMHOLE_DISABLE_QSBR and
// NDEBUG on and off. A symbol missed here shows up as a duplicate definition
// at link time.
#pragma once

#define a2s32                           diva_valuelog_a2s32
#define a2s64                           diva_valuelog_a2s64
#define a2u32                           diva_valuelog_a2u32
#define a2u64                           diva_valuelog_a2u64
#define bits_p2_down_u32                diva_valuelog_bits_p2_down_u32
#define bits_p2_down_u64                diva_valuelog_bits_p2_down_u64
#define bits_p2_up_u32                  diva_valuelog_bits_p2_up_u32
#define bits_p2_up_u64                  diva_valuelog_bits_p2_up_u64
#define bits_reverse_u32                diva_valuelog_bits_reverse_u32
#define bits_reverse_u64                diva_valuelog_bits_reverse_u64
#define bits_rotl_u32                   diva_valuelog_bits_rotl_u32
#define bits_rotl_u64                   diva_valuelog_bits_rotl_u64
#define bits_rotr_u32                   diva_valuelog_bits_rotr_u32
#define bits_rotr_u64                   diva_valuelog_bits_rotr_u64
#define bits_round_down                 diva_valuelog_bits_round_down
#define bits_round_down_a               diva_valuelog_bits_round_down_a
#define bits_round_up                   diva_valuelog_bits_round_up
#define bits_round_up_a                 diva_valuelog_bits_round_up_a
#define calloc_2d                       diva_valuelog_calloc_2d
#define co_back                         diva_valuelog_co_back
#define co_create                       diva_valuelog_co_create
#define co_destroy                      diva_valuelog_co_destroy
#define co_enter                        diva_valuelog_co_enter
#define co_exit                         diva_valuelog_co_exit
#define co_fork                         diva_valuelog_co_fork
#define co_priv                         diva_valuelog_co_priv
#define co_reuse                        diva_valuelog_co_reuse
#define corr_create                     diva_valuelog_corr_create
#define corr_destroy                    diva_valuelog_corr_destroy
#define corr_enter                      diva_valuelog_corr_enter
#define corr_exit                       diva_valuelog_corr_exit
#define corr_link                       diva_valuelog_corr_link
#define corr_relink                     diva_valuelog_corr_relink
#define corr_reuse                      diva_valuelog_corr_reuse
#define corr_yield                      diva_valuelog_corr_yield
#define co_self                         diva_valuelog_co_self
#define co_switch_stack                 diva_valuelog_co_switch_stack
#define co_switch_to                    diva_valuelog_co_switch_to
#define co_valid                        diva_valuelog_co_valid
#define cpu_cfence                      diva_valuelog_cpu_cfence
#define cpu_mfence                      diva_valuelog_cpu_mfence
#define cpu_pause                       diva_valuelog_cpu_pause
#define cpu_prefetch0                   diva_valuelog_cpu_prefetch0
#define cpu_prefetch1                   diva_valuelog_cpu_prefetch1
#define cpu_prefetch2                   diva_valuelog_cpu_prefetch2
#define cpu_prefetch3                   diva_valuelog_cpu_prefetch3
#define cpu_prefetchw                   diva_valuelog_cpu_prefetchw
#define crc32c_inc                      diva_valuelog_crc32c_inc
#define crc32c_inc_123                  diva_valuelog_crc32c_inc_123
#define crc32c_inc_x4                   diva_valuelog_crc32c_inc_x4
#define crc32c_u16                      diva_valuelog_crc32c_u16
#define crc32c_u32                      diva_valuelog_crc32c_u32
#define crc32c_u64                      diva_valuelog_crc32c_u64
#define crc32c_u8                       diva_valuelog_crc32c_u8
// A function only without NDEBUG; with it, lib.h defines debug_assert as a
// no-op function-like macro, which this name must not replace.
#ifndef NDEBUG
#define debug_assert                    diva_valuelog_debug_assert
#endif
#define debug_break                     diva_valuelog_debug_break
#define debug_die                       diva_valuelog_debug_die
#define debug_die_perror                diva_valuelog_debug_die_perror
#define debug_dump_maps                 diva_valuelog_debug_dump_maps
#define debug_perf_switch               diva_valuelog_debug_perf_switch
#define entry13                         diva_valuelog_entry13
#define entry13_update_e3               diva_valuelog_entry13_update_e3
#define fdsize                          diva_valuelog_fdsize
#define gcd64                           diva_valuelog_gcd64
#define key_size                        diva_valuelog_key_size
#define key_size_align                  diva_valuelog_key_size_align
#define kref_compare                    diva_valuelog_kref_compare
#define kref_k128_compare               diva_valuelog_kref_k128_compare
#define kref_kv128_compare              diva_valuelog_kref_kv128_compare
#define kref_kv_compare                 diva_valuelog_kref_kv_compare
#define kref_kv_lcp                     diva_valuelog_kref_kv_lcp
#define kref_kv_match                   diva_valuelog_kref_kv_match
#define kref_lcp                        diva_valuelog_kref_lcp
#define kref_match                      diva_valuelog_kref_match
#define kref_null                       diva_valuelog_kref_null
#define kref_ref_hash32                 diva_valuelog_kref_ref_hash32
#define kref_ref_kv                     diva_valuelog_kref_ref_kv
#define kref_ref_kv_hash32              diva_valuelog_kref_ref_kv_hash32
#define kref_ref_raw                    diva_valuelog_kref_ref_raw
#define kref_update_hash32              diva_valuelog_kref_update_hash32
#define kv128_decode_kv                 diva_valuelog_kv128_decode_kv
#define kv128_encode_kv                 diva_valuelog_kv128_encode_kv
#define kv128_estimate_kv               diva_valuelog_kv128_estimate_kv
#define kv128_size                      diva_valuelog_kv128_size
#define kv_compare                      diva_valuelog_kv_compare
#define kv_crc32c                       diva_valuelog_kv_crc32c
#define kv_crc32c_extend                diva_valuelog_kv_crc32c_extend
#define kv_create                       diva_valuelog_kv_create
#define kv_create_kref                  diva_valuelog_kv_create_kref
#define kv_create_str                   diva_valuelog_kv_create_str
#define kv_create_str_str               diva_valuelog_kv_create_str_str
#define kv_dup                          diva_valuelog_kv_dup
#define kv_dup2                         diva_valuelog_kv_dup2
#define kv_dup2_key                     diva_valuelog_kv_dup2_key
#define kv_dup2_key_prefix              diva_valuelog_kv_dup2_key_prefix
#define kv_dup_key                      diva_valuelog_kv_dup_key
#define kv_k128_compare                 diva_valuelog_kv_k128_compare
#define kv_key_lcp                      diva_valuelog_kv_key_lcp
#define kv_key_lcp_skip                 diva_valuelog_kv_key_lcp_skip
#define kv_kptr                         diva_valuelog_kv_kptr
#define kv_kptr_c                       diva_valuelog_kv_kptr_c
#define kv_kref                         diva_valuelog_kv_kref
#define kv_kv128_compare                diva_valuelog_kv_kv128_compare
#define kvmap_api_helper                diva_valuelog_kvmap_api_helper
#define kvmap_api_helper_message        diva_valuelog_kvmap_api_helper_message
#define kvmap_api_register              diva_valuelog_kvmap_api_register
#define kvmap_api_whsafe                diva_valuelog_kvmap_api_whsafe
#define kvmap_api_whsafe_int            diva_valuelog_kvmap_api_whsafe_int
#define kvmap_api_whunsafe              diva_valuelog_kvmap_api_whunsafe
#define kvmap_api_wormhole              diva_valuelog_kvmap_api_wormhole
#define kvmap_api_wormhole_int          diva_valuelog_kvmap_api_wormhole_int
#define kvmap_dump_keys                 diva_valuelog_kvmap_dump_keys
#define kvmap_inp_steal_kv              diva_valuelog_kvmap_inp_steal_kv
#define kvmap_kv64_del                  diva_valuelog_kvmap_kv64_del
#define kvmap_kv64_get                  diva_valuelog_kvmap_kv64_get
#define kvmap_kv64_iter_peek            diva_valuelog_kvmap_kv64_iter_peek
#define kvmap_kv64_iter_seek            diva_valuelog_kvmap_kv64_iter_seek
#define kvmap_kv64_probe                diva_valuelog_kvmap_kv64_probe
#define kvmap_kv64_put                  diva_valuelog_kvmap_kv64_put
#define kvmap_kv_del                    diva_valuelog_kvmap_kv_del
#define kvmap_kv_delr                   diva_valuelog_kvmap_kv_delr
#define kvmap_kv_get                    diva_valuelog_kvmap_kv_get
#define kvmap_kv_inpr                   diva_valuelog_kvmap_kv_inpr
#define kvmap_kv_inpw                   diva_valuelog_kvmap_kv_inpw
#define kvmap_kv_iter_seek              diva_valuelog_kvmap_kv_iter_seek
#define kvmap_kv_merge                  diva_valuelog_kvmap_kv_merge
#define kvmap_kv_probe                  diva_valuelog_kvmap_kv_probe
#define kvmap_kv_put                    diva_valuelog_kvmap_kv_put
#define kvmap_mm_dup                    diva_valuelog_kvmap_mm_dup
#define kvmap_mm_free_free              diva_valuelog_kvmap_mm_free_free
#define kvmap_mm_free_noop              diva_valuelog_kvmap_mm_free_noop
#define kvmap_mm_in_dup                 diva_valuelog_kvmap_mm_in_dup
#define kvmap_mm_in_noop                diva_valuelog_kvmap_mm_in_noop
#define kvmap_mm_ndf                    diva_valuelog_kvmap_mm_ndf
#define kvmap_mm_out_dup                diva_valuelog_kvmap_mm_out_dup
#define kvmap_mm_out_noop               diva_valuelog_kvmap_mm_out_noop
#define kvmap_raw_del                   diva_valuelog_kvmap_raw_del
#define kvmap_raw_get                   diva_valuelog_kvmap_raw_get
#define kvmap_raw_inpr                  diva_valuelog_kvmap_raw_inpr
#define kvmap_raw_inpw                  diva_valuelog_kvmap_raw_inpw
#define kvmap_raw_iter_seek             diva_valuelog_kvmap_raw_iter_seek
#define kvmap_raw_probe                 diva_valuelog_kvmap_raw_probe
#define kvmap_ref                       diva_valuelog_kvmap_ref
#define kvmap_unref                     diva_valuelog_kvmap_unref
#define kv_match                        diva_valuelog_kv_match
#define kv_match_full                   diva_valuelog_kv_match_full
#define kv_match_hash                   diva_valuelog_kv_match_hash
#define kv_match_kv128                  diva_valuelog_kv_match_kv128
#define kv_null                         diva_valuelog_kv_null
#define kv_print                        diva_valuelog_kv_print
#define kv_psort                        diva_valuelog_kv_psort
#define kv_qsort                        diva_valuelog_kv_qsort
#define kvref_dup2_key                  diva_valuelog_kvref_dup2_key
#define kvref_dup2_kv                   diva_valuelog_kvref_dup2_kv
#define kv_refill                       diva_valuelog_kv_refill
#define kv_refill_hex32                 diva_valuelog_kv_refill_hex32
#define kv_refill_hex64                 diva_valuelog_kv_refill_hex64
#define kv_refill_hex64_klen            diva_valuelog_kv_refill_hex64_klen
#define kv_refill_kref                  diva_valuelog_kv_refill_kref
#define kv_refill_kref_v                diva_valuelog_kv_refill_kref_v
#define kv_refill_str                   diva_valuelog_kv_refill_str
#define kv_refill_str_str               diva_valuelog_kv_refill_str_str
#define kv_refill_u64                   diva_valuelog_kv_refill_u64
#define kv_refill_value                 diva_valuelog_kv_refill_value
#define kvref_kv_compare                diva_valuelog_kvref_kv_compare
#define kvref_ref_kv                    diva_valuelog_kvref_ref_kv
#define kv_size                         diva_valuelog_kv_size
#define kv_size_align                   diva_valuelog_kv_size_align
#define kv_update_hash                  diva_valuelog_kv_update_hash
#define kv_vptr                         diva_valuelog_kv_vptr
#define kv_vptr_c                       diva_valuelog_kv_vptr_c
#define logger_printf                   diva_valuelog_logger_printf
#define malloc_2d                       diva_valuelog_malloc_2d
#define memlcp                          diva_valuelog_memlcp
#define mhash32                         diva_valuelog_mhash32
#define mhash64                         diva_valuelog_mhash64
#define m_usable_size                   diva_valuelog_m_usable_size
#define mutex_deinit                    diva_valuelog_mutex_deinit
#define mutex_init                      diva_valuelog_mutex_init
#define mutex_lock                      diva_valuelog_mutex_lock
#define mutex_trylock                   diva_valuelog_mutex_trylock
#define mutex_unlock                    diva_valuelog_mutex_unlock
#define pages_alloc_1gb                 diva_valuelog_pages_alloc_1gb
#define pages_alloc_2mb                 diva_valuelog_pages_alloc_2mb
#define pages_alloc_4kb                 diva_valuelog_pages_alloc_4kb
#define pages_alloc_best                diva_valuelog_pages_alloc_best
#define pages_lock                      diva_valuelog_pages_lock
#define pages_unmap                     diva_valuelog_pages_unmap
#define process_affinity_count          diva_valuelog_process_affinity_count
#define process_cpu_time_usec           diva_valuelog_process_cpu_time_usec
#define process_getaffinity_list        diva_valuelog_process_getaffinity_list
#define process_get_rss                 diva_valuelog_process_get_rss
#define ptr_to_u64                      diva_valuelog_ptr_to_u64
#define qsbr_create                     diva_valuelog_qsbr_create
#define qsbr_destroy                    diva_valuelog_qsbr_destroy
#define qsbr_park                       diva_valuelog_qsbr_park
#define qsbr_register                   diva_valuelog_qsbr_register
#define qsbr_resume                     diva_valuelog_qsbr_resume
#define qsbr_unregister                 diva_valuelog_qsbr_unregister
#define qsbr_update                     diva_valuelog_qsbr_update
#define qsbr_wait                       diva_valuelog_qsbr_wait
#define random_double                   diva_valuelog_random_double
#define random_u64                      diva_valuelog_random_u64
#define rwlock_init                     diva_valuelog_rwlock_init
#define rwlock_lock_read                diva_valuelog_rwlock_lock_read
#define rwlock_lock_write               diva_valuelog_rwlock_lock_write
#define rwlock_lock_write_hp            diva_valuelog_rwlock_lock_write_hp
#define rwlock_trylock_read             diva_valuelog_rwlock_trylock_read
#define rwlock_trylock_read_lp          diva_valuelog_rwlock_trylock_read_lp
#define rwlock_trylock_read_nr          diva_valuelog_rwlock_trylock_read_nr
#define rwlock_trylock_upgrade_write    diva_valuelog_rwlock_trylock_upgrade_write
#define rwlock_trylock_write            diva_valuelog_rwlock_trylock_write
#define rwlock_trylock_write_hp         diva_valuelog_rwlock_trylock_write_hp
#define rwlock_trylock_write_hp_nr      diva_valuelog_rwlock_trylock_write_hp_nr
#define rwlock_trylock_write_nr         diva_valuelog_rwlock_trylock_write_nr
#define rwlock_unlock_read              diva_valuelog_rwlock_unlock_read
#define rwlock_unlock_write             diva_valuelog_rwlock_unlock_write
#define rwlock_write_to_read            diva_valuelog_rwlock_write_to_read
#define slab_alloc_safe                 diva_valuelog_slab_alloc_safe
#define slab_alloc_unsafe               diva_valuelog_slab_alloc_unsafe
#define slab_create                     diva_valuelog_slab_create
#define slab_destroy                    diva_valuelog_slab_destroy
#define slab_free_all                   diva_valuelog_slab_free_all
#define slab_free_safe                  diva_valuelog_slab_free_safe
#define slab_free_unsafe                diva_valuelog_slab_free_unsafe
#define slab_get_nalloc                 diva_valuelog_slab_get_nalloc
#define slab_reserve_unsafe             diva_valuelog_slab_reserve_unsafe
#define spinlock_init                   diva_valuelog_spinlock_init
#define spinlock_lock                   diva_valuelog_spinlock_lock
#define spinlock_trylock                diva_valuelog_spinlock_trylock
#define spinlock_unlock                 diva_valuelog_spinlock_unlock
#define srandom_u64                     diva_valuelog_srandom_u64
#define strdec_32                       diva_valuelog_strdec_32
#define strdec_64                       diva_valuelog_strdec_64
#define strhex_32                       diva_valuelog_strhex_32
#define strhex_64                       diva_valuelog_strhex_64
#define str_print_dec                   diva_valuelog_str_print_dec
#define str_print_hex                   diva_valuelog_str_print_hex
#define strtoks                         diva_valuelog_strtoks
#define strtoks_count                   diva_valuelog_strtoks_count
#define thread_create_at                diva_valuelog_thread_create_at
#define thread_fork_join                diva_valuelog_thread_fork_join
#define thread_get_name                 diva_valuelog_thread_get_name
#define thread_pin                      diva_valuelog_thread_pin
#define thread_setaffinity_list         diva_valuelog_thread_setaffinity_list
#define thread_set_name                 diva_valuelog_thread_set_name
#define time_diff_nsec                  diva_valuelog_time_diff_nsec
#define time_diff_sec                   diva_valuelog_time_diff_sec
#define time_nsec                       diva_valuelog_time_nsec
#define time_sec                        diva_valuelog_time_sec
#define time_stamp                      diva_valuelog_time_stamp
#define time_stamp2                     diva_valuelog_time_stamp2
#define u64_to_ptr                      diva_valuelog_u64_to_ptr
#define vi128_decode_u32                diva_valuelog_vi128_decode_u32
#define vi128_decode_u64                diva_valuelog_vi128_decode_u64
#define vi128_encode_u32                diva_valuelog_vi128_encode_u32
#define vi128_encode_u64                diva_valuelog_vi128_encode_u64
#define vi128_estimate_u32              diva_valuelog_vi128_estimate_u32
#define vi128_estimate_u64              diva_valuelog_vi128_estimate_u64
#define watch_u64_usr1                  diva_valuelog_watch_u64_usr1
#define wh_clean                        diva_valuelog_wh_clean
#define wh_create                       diva_valuelog_wh_create
#define wh_del                          diva_valuelog_wh_del
#define wh_delr                         diva_valuelog_wh_delr
#define wh_destroy                      diva_valuelog_wh_destroy
#define wh_get                          diva_valuelog_wh_get
#define wh_inpr                         diva_valuelog_wh_inpr
#define wh_inpw                         diva_valuelog_wh_inpw
#define wh_int_clean                    diva_valuelog_wh_int_clean
#define wh_int_create                   diva_valuelog_wh_int_create
#define wh_int_del                      diva_valuelog_wh_int_del
#define wh_int_delr                     diva_valuelog_wh_int_delr
#define wh_int_destroy                  diva_valuelog_wh_int_destroy
#define wh_int_get                      diva_valuelog_wh_int_get
#define wh_int_inpr                     diva_valuelog_wh_int_inpr
#define wh_int_inpw                     diva_valuelog_wh_int_inpw
#define wh_int_iter_create              diva_valuelog_wh_int_iter_create
#define wh_int_iter_destroy             diva_valuelog_wh_int_iter_destroy
#define wh_int_iter_inp                 diva_valuelog_wh_int_iter_inp
#define wh_int_iter_park                diva_valuelog_wh_int_iter_park
#define wh_int_iter_peek                diva_valuelog_wh_int_iter_peek
#define wh_int_iter_peek_ref            diva_valuelog_wh_int_iter_peek_ref
#define wh_int_iter_seek                diva_valuelog_wh_int_iter_seek
#define wh_int_iter_skip                diva_valuelog_wh_int_iter_skip
#define wh_int_iter_skip1               diva_valuelog_wh_int_iter_skip1
#define wh_int_iter_skip1_rev           diva_valuelog_wh_int_iter_skip1_rev
#define wh_int_iter_valid               diva_valuelog_wh_int_iter_valid
#define wh_int_merge                    diva_valuelog_wh_int_merge
#define wh_int_park                     diva_valuelog_wh_int_park
#define wh_int_probe                    diva_valuelog_wh_int_probe
#define wh_int_put                      diva_valuelog_wh_int_put
#define wh_int_ref                      diva_valuelog_wh_int_ref
#define wh_int_resume                   diva_valuelog_wh_int_resume
#define wh_int_unref                    diva_valuelog_wh_int_unref
#define wh_iter_create                  diva_valuelog_wh_iter_create
#define wh_iter_destroy                 diva_valuelog_wh_iter_destroy
#define wh_iter_inp                     diva_valuelog_wh_iter_inp
#define wh_iter_park                    diva_valuelog_wh_iter_park
#define wh_iter_peek                    diva_valuelog_wh_iter_peek
#define wh_iter_peek_ref                diva_valuelog_wh_iter_peek_ref
#define wh_iter_seek                    diva_valuelog_wh_iter_seek
#define wh_iter_seek_pred               diva_valuelog_wh_iter_seek_pred
#define wh_iter_seek_pred_strict        diva_valuelog_wh_iter_seek_pred_strict
#define wh_iter_skip                    diva_valuelog_wh_iter_skip
#define wh_iter_skip1                   diva_valuelog_wh_iter_skip1
#define wh_iter_skip1_rev               diva_valuelog_wh_iter_skip1_rev
#define wh_iter_valid                   diva_valuelog_wh_iter_valid
#define wh_merge                        diva_valuelog_wh_merge
#define wh_park                         diva_valuelog_wh_park
#define wh_probe                        diva_valuelog_wh_probe
#define wh_put                          diva_valuelog_wh_put
#define wh_ref                          diva_valuelog_wh_ref
#define wh_resume                       diva_valuelog_wh_resume
#define whsafe_del                      diva_valuelog_whsafe_del
#define whsafe_delr                     diva_valuelog_whsafe_delr
#define whsafe_get                      diva_valuelog_whsafe_get
#define whsafe_inpr                     diva_valuelog_whsafe_inpr
#define whsafe_inpw                     diva_valuelog_whsafe_inpw
#define whsafe_int_del                  diva_valuelog_whsafe_int_del
#define whsafe_int_delr                 diva_valuelog_whsafe_int_delr
#define whsafe_int_get                  diva_valuelog_whsafe_int_get
#define whsafe_int_iter_destroy         diva_valuelog_whsafe_int_iter_destroy
#define whsafe_int_iter_park            diva_valuelog_whsafe_int_iter_park
#define whsafe_int_iter_seek            diva_valuelog_whsafe_int_iter_seek
#define whsafe_int_merge                diva_valuelog_whsafe_int_merge
#define whsafe_int_probe                diva_valuelog_whsafe_int_probe
#define whsafe_int_put                  diva_valuelog_whsafe_int_put
#define whsafe_int_ref                  diva_valuelog_whsafe_int_ref
#define whsafe_iter_destroy             diva_valuelog_whsafe_iter_destroy
#define whsafe_iter_next                diva_valuelog_whsafe_iter_next
#define whsafe_iter_park                diva_valuelog_whsafe_iter_park
#define whsafe_iter_seek                diva_valuelog_whsafe_iter_seek
#define whsafe_iter_seek_pred           diva_valuelog_whsafe_iter_seek_pred
#define whsafe_iter_seek_pred_strict    diva_valuelog_whsafe_iter_seek_pred_strict
#define whsafe_iter_skip                diva_valuelog_whsafe_iter_skip
#define whsafe_iter_skip1               diva_valuelog_whsafe_iter_skip1
#define whsafe_iter_skip1_rev           diva_valuelog_whsafe_iter_skip1_rev
#define whsafe_merge                    diva_valuelog_whsafe_merge
#define whsafe_probe                    diva_valuelog_whsafe_probe
#define whsafe_put                      diva_valuelog_whsafe_put
#define whsafe_ref                      diva_valuelog_whsafe_ref
#define wh_unref                        diva_valuelog_wh_unref
#define whunsafe_create                 diva_valuelog_whunsafe_create
#define whunsafe_del                    diva_valuelog_whunsafe_del
#define whunsafe_delr                   diva_valuelog_whunsafe_delr
#define whunsafe_get                    diva_valuelog_whunsafe_get
#define whunsafe_inp                    diva_valuelog_whunsafe_inp
#define whunsafe_int_create             diva_valuelog_whunsafe_int_create
#define whunsafe_int_del                diva_valuelog_whunsafe_int_del
#define whunsafe_int_delr               diva_valuelog_whunsafe_int_delr
#define whunsafe_int_get                diva_valuelog_whunsafe_int_get
#define whunsafe_int_merge              diva_valuelog_whunsafe_int_merge
#define whunsafe_int_probe              diva_valuelog_whunsafe_int_probe
#define whunsafe_int_put                diva_valuelog_whunsafe_int_put
#define whunsafe_iter_create            diva_valuelog_whunsafe_iter_create
#define whunsafe_iter_destroy           diva_valuelog_whunsafe_iter_destroy
#define whunsafe_iter_next              diva_valuelog_whunsafe_iter_next
#define whunsafe_iter_seek              diva_valuelog_whunsafe_iter_seek
#define whunsafe_iter_skip              diva_valuelog_whunsafe_iter_skip
#define whunsafe_iter_skip1             diva_valuelog_whunsafe_iter_skip1
#define whunsafe_merge                  diva_valuelog_whunsafe_merge
#define whunsafe_probe                  diva_valuelog_whunsafe_probe
#define whunsafe_put                    diva_valuelog_whunsafe_put
#define wormhole_clean                  diva_valuelog_wormhole_clean
#define wormhole_create                 diva_valuelog_wormhole_create
#define wormhole_del                    diva_valuelog_wormhole_del
#define wormhole_delr                   diva_valuelog_wormhole_delr
#define wormhole_destroy                diva_valuelog_wormhole_destroy
#define wormhole_fprint                 diva_valuelog_wormhole_fprint
#define wormhole_get                    diva_valuelog_wormhole_get
#define wormhole_inpr                   diva_valuelog_wormhole_inpr
#define wormhole_inpw                   diva_valuelog_wormhole_inpw
#define wormhole_int_clean              diva_valuelog_wormhole_int_clean
#define wormhole_int_create             diva_valuelog_wormhole_int_create
#define wormhole_int_del                diva_valuelog_wormhole_int_del
#define wormhole_int_delr               diva_valuelog_wormhole_int_delr
#define wormhole_int_destroy            diva_valuelog_wormhole_int_destroy
#define wormhole_int_fprint             diva_valuelog_wormhole_int_fprint
#define wormhole_int_get                diva_valuelog_wormhole_int_get
#define wormhole_int_iter_create        diva_valuelog_wormhole_int_iter_create
#define wormhole_int_iter_destroy       diva_valuelog_wormhole_int_iter_destroy
#define wormhole_int_iter_inp           diva_valuelog_wormhole_int_iter_inp
#define wormhole_int_iter_kref          diva_valuelog_wormhole_int_iter_kref
#define wormhole_int_iter_kvref         diva_valuelog_wormhole_int_iter_kvref
#define wormhole_int_iter_next          diva_valuelog_wormhole_int_iter_next
#define wormhole_int_iter_park          diva_valuelog_wormhole_int_iter_park
#define wormhole_int_iter_peek          diva_valuelog_wormhole_int_iter_peek
#define wormhole_int_iter_prev          diva_valuelog_wormhole_int_iter_prev
#define wormhole_int_iter_seek          diva_valuelog_wormhole_int_iter_seek
#define wormhole_int_iter_skip          diva_valuelog_wormhole_int_iter_skip
#define wormhole_int_iter_skip1         diva_valuelog_wormhole_int_iter_skip1
#define wormhole_int_iter_skip1_rev     diva_valuelog_wormhole_int_iter_skip1_rev
#define wormhole_int_iter_valid         diva_valuelog_wormhole_int_iter_valid
#define wormhole_int_merge              diva_valuelog_wormhole_int_merge
#define wormhole_int_park               diva_valuelog_wormhole_int_park
#define wormhole_int_probe              diva_valuelog_wormhole_int_probe
#define wormhole_int_put                diva_valuelog_wormhole_int_put
#define wormhole_int_ref                diva_valuelog_wormhole_int_ref
#define wormhole_int_refresh_qstate     diva_valuelog_wormhole_int_refresh_qstate
#define wormhole_int_resume             diva_valuelog_wormhole_int_resume
#define wormhole_int_unref              diva_valuelog_wormhole_int_unref
#define wormhole_iter_create            diva_valuelog_wormhole_iter_create
#define wormhole_iter_destroy           diva_valuelog_wormhole_iter_destroy
#define wormhole_iter_inp               diva_valuelog_wormhole_iter_inp
#define wormhole_iter_kref              diva_valuelog_wormhole_iter_kref
#define wormhole_iter_kvref             diva_valuelog_wormhole_iter_kvref
#define wormhole_iter_next              diva_valuelog_wormhole_iter_next
#define wormhole_iter_park              diva_valuelog_wormhole_iter_park
#define wormhole_iter_peek              diva_valuelog_wormhole_iter_peek
#define wormhole_iter_prev              diva_valuelog_wormhole_iter_prev
#define wormhole_iter_seek              diva_valuelog_wormhole_iter_seek
#define wormhole_iter_seek_pred         diva_valuelog_wormhole_iter_seek_pred
#define wormhole_iter_seek_pred_strict  diva_valuelog_wormhole_iter_seek_pred_strict
#define wormhole_iter_skip              diva_valuelog_wormhole_iter_skip
#define wormhole_iter_skip1             diva_valuelog_wormhole_iter_skip1
#define wormhole_iter_skip1_rev         diva_valuelog_wormhole_iter_skip1_rev
#define wormhole_iter_valid             diva_valuelog_wormhole_iter_valid
#define wormhole_merge                  diva_valuelog_wormhole_merge
#define wormhole_park                   diva_valuelog_wormhole_park
#define wormhole_probe                  diva_valuelog_wormhole_probe
#define wormhole_put                    diva_valuelog_wormhole_put
#define wormhole_ref                    diva_valuelog_wormhole_ref
#define wormhole_refresh_qstate         diva_valuelog_wormhole_refresh_qstate
#define wormhole_resume                 diva_valuelog_wormhole_resume
#define wormhole_unref                  diva_valuelog_wormhole_unref
#define wormleaf_int_lock_read          diva_valuelog_wormleaf_int_lock_read
#define wormleaf_int_lock_upgrade_write diva_valuelog_wormleaf_int_lock_upgrade_write
#define wormleaf_int_lock_write         diva_valuelog_wormleaf_int_lock_write
#define wormleaf_int_unlock_read        diva_valuelog_wormleaf_int_unlock_read
#define wormleaf_int_unlock_write       diva_valuelog_wormleaf_int_unlock_write
#define wormleaf_lock_read              diva_valuelog_wormleaf_lock_read
#define wormleaf_lock_upgrade_write     diva_valuelog_wormleaf_lock_upgrade_write
#define wormleaf_lock_write             diva_valuelog_wormleaf_lock_write
#define wormleaf_unlock_read            diva_valuelog_wormleaf_unlock_read
#define wormleaf_unlock_write           diva_valuelog_wormleaf_unlock_write
#define xalloc                          diva_valuelog_xalloc
#define yalloc                          diva_valuelog_yalloc
